version: '3.8'

services:
  test_web:
    container_name: api_test
    build: .
    entrypoint:
      sh -c "echo 'Starting tests...' &&
      pytest -vv"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.tests
    networks:
      - test_network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  test_db:
    container_name: db_test
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env.tests
    ports:
      - "8080:5432"
    networks:
      - test_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 60s
      retries: 5

  test_redis:
    container_name: redis_test
    image: redis:latest
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf://usr/local/etc/redis/redis.conf
    expose:
      - 6379
    ports:
      - "9000:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - test_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 20s
      retries: 100

volumes:
  postgres_data:

networks:
  test_network:
    name: test_network
