version: '3.8'

services:
  test_web:
    container_name: test
    build: .
    command: sh -c "echo 'Starting tests...' && pytest -vv"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/test
      - SQLALCHEMY_SILENCE_UBER_WARNING=1
    networks:
      - test_network


networks:
  test_network:
    external:
      name: common_network
